# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "init" ]
  pull_request:
    branches: [ "init" ]

env:
  GOLANG_VERSION: 1.21.x

jobs:


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go ${{ env.GOLANG_VERSION }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GOLANG_VERSION }}

    - name: Build
      run: go build -o ../bin/workshop -v ./...
      working-directory: workshop-service

    - name: Test
      run: go test -v ./...
      working-directory: workshop-service
